services:
  postgres:
    image: postgres:15
    container_name: expense-tracker-postgres
    restart: always
    env_file:
      - ./expensetracker/.env.docker
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data_15:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: expense-tracker-pgadmin
    restart: always
    env_file:
      - ./expensetracker/.env.docker
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  backend:
    image: ermolz/expense-tracker-backend:latest
    container_name: expense-tracker-backend
    restart: always
    env_file:
      - ./expensetracker/.env.docker
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_ACCESS_EXPIRATION: ${JWT_ACCESS_EXPIRATION_MS}
      JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION_MS}
      FILE_UPLOAD_DIR: /app/uploads
    volumes:
      - app_uploads:/app/uploads
      - app_logs:/app/logs
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    image: ermolz/expense-tracker-frontend:latest
    container_name: expense-tracker-frontend
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  pg_data_15:
  app_uploads:
  app_logs:

networks:
  app-network:
    driver: bridge
